name: jagger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_stripe: 2.0.0
  cloud_functions: 3.0.4
  flutter_launcher_icons: 0.8.0
  cloud_firestore: 2.5.3
  cupertino_icons: ^1.0.2
  dropdownfield: ^1.0.3
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  table_calendar: ^3.0.3
  numberpicker: ^2.1.1
  photo_view: ^0.13.0
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo.jpg"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
